services:
  pgdatabase:

  # --- ORIGINAL SETUP (Commented out for reference) ---
    # image: pgvector/pgvector:pg18


    # --- NEW PG_CRON SETUP ---
    build:
      context: .
      dockerfile: pg_cron-dockerfile
    ########################################################


    container_name: postgres_18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_1
    volumes:
      - "./db_postgres_data:/var/lib/postgresql"
      # This is your WSL2 folder for easy CSV imports!
      - "./datasets/data:/data:ro" 
    ports:
      - "5432:5432"



    # --- NEW PG_CRON SETUP ---
    command: |
      postgres 
      -c shared_preload_libraries='pg_cron' 
      -c cron.database_name='bookly'
    ######################################################


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=iceyisaak@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - "./datasets/data:/var/lib/pgadmin/storage/iceyisaak_gmail.com/imports:ro"
      - "./exports:/var/lib/pgadmin/storage/iceyisaak_gmail.com/exports"
    ports:
      - "8080:80"

volumes:
  pgadmin_data:

# networks:
#   shared_db_network:
#     name: common_pg_network 